services:
  server:
    build: .
    ports:
      - "3002:3002"
    command: node ./bin/server.js --no-colors
    env_file: .env
    depends_on:
      - minio
      - redis

  worker:
    build: .
    command: node ./bin/worker.js --no-colors
    env_file: .env
    depends_on:
      - minio
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  auth:
    build: ./auth
    ports:
      - "5175:5175"
    env_file: .env
    depends_on:
      - server

  minio:
    image: quay.io/minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address :9001
